# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c0989768a3bc3d3b19eccdfd1ae17491b8d181571ff7d7deaf664736ba1f1b7191e587e938bb28f5a5f77cf136cd31905e77375e8bb63ff900c5eb321d14ee07

test:
  secret_key_base: abe30f3f72fa1f633db7b44922618886667310e83bc34b8e0a22fb39c44c3a0db206aa47c5939af4831d846bc710e6f87e501fbf4db499586bed54ccca942a62

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
